import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Art Heist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the <a href="/"><b>NFT Art Heist</b></a> Workshop!
        </h1>

        <p className={styles.description}>
          Get started by <a href="/signin">signing in</a> or <a href="/signup">creating an account</a>.
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
          <a href="/art" className={styles.card}>
            <h2>🖼 The Art &rarr;</h2>
            <p>Click here to see the progress of art restoration.</p>
          </a>

          <a href="/test" className={styles.card}>
            <h2>🧪 Test &rarr;</h2>
            <p>Click here to test your NFT-Art-Restorer.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.bitproject.org/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Bit Project&nbsp;&nbsp;
          <span>
            <Image src="https://www.bitproject.org/logo.png" alt="Bit Project Logo" width={30} height={30} />
          </span>
        </a>
      </footer>
    </div>
  )
}
